import { test, expect } from '@playwright/test'

test('real backend: both maps, shared orders, explanation, pause and reset', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('img', { name: 'Baseline map of Monterrey' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Smart map of Monterrey' })).toBeVisible()
  await page.screenshot({ path: '../artifacts/frontend/desktop-start.png', fullPage: true })
  await page.getByRole('button', { name: '▶ Start', exact: true }).click()
  await expect(page.locator('.stream-indicator')).toContainText('Same order stream', { timeout: 150000 })
  await expect(page.locator('.current-order strong').first()).toContainText('ORD-00001')
  await expect(page.locator('.current-order strong').last()).toContainText('ORD-00001')
  await expect(page.locator('.order-card')).toHaveCount(1)
  await page.locator('.order-card .why summary').first().click()
  await expect(page.locator('.explanation').first()).toBeVisible()
  // Let actual playback reach Smart's first accepted order. Baseline may skip it.
  await expect(page.locator('.map-current-order').last()).not.toContainText('Sin orden activa', { timeout: 45000 })
  await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click()
  await expect(page.getByText('Ⅱ Playback paused')).toBeVisible()
  const clock = await page.locator('.clock strong').textContent()
  await page.waitForTimeout(600)
  expect(await page.locator('.clock strong').textContent()).toBe(clock)
  await page.screenshot({ path: '../artifacts/frontend/desktop-active.png', fullPage: true })
  await page.setViewportSize({ width: 1920, height: 1080 })
  await page.screenshot({ path: '../artifacts/frontend/desktop-1920.png', fullPage: true })
  await page.getByText('Inject Event', { exact: false }).click()
  await page.getByRole('button', { name: 'Road Closure', exact: true }).click()
  await expect(page.locator('.shock-card').filter({ hasText: 'Road closure' })).toBeVisible({ timeout: 150000 })
  await expect(page.locator('.error-banner')).toHaveCount(0)
  await page.screenshot({ path: '../artifacts/frontend/desktop-closure.png', fullPage: true })
  await page.getByRole('button', { name: 'Reset simulation' }).click()
  await expect(page.locator('.order-card')).toHaveCount(0)
  await expect(page.locator('.current-order strong').first()).toHaveText('Waiting for first order')
  expect(errors).toEqual([])
})
